-- 코드를 입력하세요
SELECT YEAR(b.SALES_DATE) as YEAR, MONTH(b.SALES_DATE) as MONTH, COUNT(DISTINCT(b.USER_ID)) as PURCHASED_USERS,
ROUND(COUNT(DISTINCT(b.USER_ID)) / total.total_count,1) as PUCHASED_RATIO
FROM (
    SELECT *
    FROM USER_INFO u
    WHERE YEAR(u.JOINED) = 2021 
) sub join ONLINE_SALE b on sub.USER_ID = b.USER_ID
CROSS JOIN (
    SELECT COUNT(*) as total_count
    FROM USER_INFO u
    WHERE YEAR(u.JOINED) = 2021
) total
GROUP BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE)
order by YEAR(b.SALES_DATE) ,MONTH(b.SALES_DATE)