-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD')
from MEMBER_PROFILE
where extract(Month from DATE_OF_BIRTH) = '3' AND GENDER = 'W' AND TLNO IS NOT NULL
order by MEMBER_ID;